version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=zekais
      - POSTGRES_PASSWORD=zekais123
      - POSTGRES_DB=bank_sampah
    networks:
      - banksampah

  pgadmin:
    image: dpage/pgadmin4
    container_name: recob-pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - dev-db
    networks:
      - banksampah

networks:
  banksampah:
